from pathlib import Path
import json
import statistics
import yaml

from .orchestrator import MultiAgentOrchestrator


def fact_coverage(answer, required_facts):
    if not required_facts:
        return 1.0
    answer = answer.lower()
    hits = sum(fact.lower() in answer for fact in required_facts)
    return hits / len(required_facts)


def source_recall(evidence, expected_sources):
    if not expected_sources:
        return 1.0
    retrieved = {item.source for item in evidence}
    hits = sum(source in retrieved for source in expected_sources)
    return hits / len(expected_sources)


def main():
    with open("config.yaml", "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    scenarios = json.loads(
        Path(cfg["evaluation"]["scenarios_path"]).read_text(encoding="utf-8")
    )

    system = MultiAgentOrchestrator.from_config("config.yaml")
    examples = []

    for scenario in scenarios:
        state = system.run(scenario["request"])

        metrics = {
            "source_recall": round(
                source_recall(state.evidence, scenario["expected_sources"]), 4
            ),
            "fact_coverage": round(
                fact_coverage(state.final_answer, scenario["required_facts"]), 4
            ),
            "workflow_completed": float(
                state.trace[-1].status == "completed"
            ),
            "critic_approved": float(
                state.critique.get("approved", False)
            ),
        }

        examples.append(
            {
                "name": scenario["name"],
                "request": scenario["request"],
                "metrics": metrics,
                "sources": [item.source for item in state.evidence],
                "final_answer": state.final_answer,
            }
        )

    metric_names = [
        "source_recall",
        "fact_coverage",
        "workflow_completed",
        "critic_approved",
    ]

    summary = {
        metric: round(
            statistics.mean(example["metrics"][metric] for example in examples),
            4,
        )
        for metric in metric_names
    }

    results = {"summary": summary, "examples": examples}

    results_path = Path(cfg["evaluation"]["results_path"])
    results_path.parent.mkdir(parents=True, exist_ok=True)
    results_path.write_text(json.dumps(results, indent=2), encoding="utf-8")

    report = [
        "# Multi-Agent System Evaluation",
        "",
        "Generated by `python -m src.evaluate`.",
        "",
        "| Metric | Score |",
        "|---|---:|",
        f"| Source Recall | {summary['source_recall']:.3f} |",
        f"| Required Fact Coverage | {summary['fact_coverage']:.3f} |",
        f"| Workflow Completion | {summary['workflow_completed']:.3f} |",
        f"| Critic Approval | {summary['critic_approved']:.3f} |",
        "",
        "## Scenario results",
        "",
        "| Scenario | Source Recall | Fact Coverage | Completed | Critic Approved |",
        "|---|---:|---:|---:|---:|",
    ]

    for example in examples:
        m = example["metrics"]
        report.append(
            f"| {example['name']} | {m['source_recall']:.3f} | "
            f"{m['fact_coverage']:.3f} | {m['workflow_completed']:.3f} | "
            f"{m['critic_approved']:.3f} |"
        )

    report.extend(
        [
            "",
            "## Notes",
            "",
            "This evaluation is intentionally small and deterministic. It is useful for regression testing the workflow, but production agent systems should also be evaluated for reasoning quality, tool selection, hallucination rate, latency, cost, safety, and failure recovery.",
        ]
    )

    Path(cfg["evaluation"]["report_path"]).write_text(
        "\n".join(report) + "\n",
        encoding="utf-8",
    )

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
